swagger: "2.0"
info:
  description: "This is API documentations for the Urparts Scraper app."
  version: "1.0.0"
  title: "Urparts Scraper"
  contact:
    email: "spsree@gmail.com"
host: "localhost:8000"
# basePath: "/api"
tags:
- name: "Parts"
  description: "Endpoints on parts"
schemes:
- "https"
- "http"
paths:
  /parts_details:
    get:
      tags:
      - "Parts"
      summary: "Get parts details"
      description: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        [  
         {  
            "name":"manufacturer",
            "in":"query",
            "description":"The manufacturer of the parts to be fetched",
            "required":false,
            "type":"string"
         },
         {  
            "name":"category",
            "in":"query",
            "description":"The category of the parts to be fetched",
            "required":false,
            "type":"string"
         },
         {  
            "name":"model",
            "in":"query",
            "description":"The model of the parts to be fetched",
            "required":false,
            "type":"string"
         },
        ]
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Parts"
        "404":
          description: "Data not found"

definitions:
  Parts:
    type: "array"
    items:
      properties:
        company_name:
          type: "string"
        category_name:
          type: "string"
        model_name:
          type: "string"
        part_name:
          type: "string"
    xml:
      name: "Parts"